services:
  # Service to create development environment with terminal
  dev:
    build: .
    working_dir: /home/epx-results
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
    command: /bin/bash

  # Service to upload to PyPI
  pypi-upload:
    build: .
    working_dir: /home/epx-results
    environment:
      - TWINE_USERNAME=${TWINE_USERNAME}
      - TWINE_PASSWORD=${TWINE_PASSWORD}
    volumes:
      - type: bind
        source: .
        target: /home/epx-results
    command: >
      sh -c "python3 -m build
             twine upload --skip-existing --repository testpypi dist/*"
