services:
  # Service to create development environment with terminal
  dev:
    build: .
    working_dir: /mnt/epx-results
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: /bin/bash

  # Service to upload to the test PyPI repository
  test-pypi-upload:
    build: .
    working_dir: /mnt/epx-results
    environment:
      - TWINE_USERNAME=${TWINE_USERNAME:-}
      - TWINE_PASSWORD=${TWINE_PASSWORD:-}
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "rm -fr dist
             python3 -m build
             twine upload --skip-existing --repository testpypi dist/*"

  # Service to upload to the PyPI repository
  pypi-upload:
    build: .
    working_dir: /mnt/epx-results
    environment:
      - TWINE_USERNAME=${TWINE_USERNAME:-}
      - TWINE_PASSWORD=${TWINE_PASSWORD:-}
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "rm -fr dist
             python3 -m build
             twine upload --repository pypi dist/*"

  # Service to check that VERSION file is valid
  check_version:
    build: .
    working_dir: /mnt/epx-results
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "pip install -r ci/requirements.txt
             python3 ci check_version"

  # Run tests for epx-results
  test:
    build: .
    working_dir: /mnt/epx-results
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "pip install .
             python3 ./scripts/generate-test-data.py
             pytest"

