services:
  # Service to create development environment with terminal
  dev:
    build: .
    working_dir: /mnt/epx-results
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: /bin/bash

  # Service to upload to the test PyPI repository
  test-pypi-upload:
    build: .
    working_dir: /mnt/epx-results
    environment:
      - TWINE_USERNAME=${TWINE_USERNAME}
      - TWINE_PASSWORD=${TWINE_PASSWORD}
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "rm -fr dist
             python3 -m build
             twine upload --skip-existing --repository testpypi dist/*"

  # Service to upload to the PyPI repository
  pypi-upload:
    build: .
    working_dir: /mnt/epx-results
    environment:
      - TWINE_USERNAME=${TWINE_USERNAME}
      - TWINE_PASSWORD=${TWINE_PASSWORD}
    volumes:
      - type: bind
        source: .
        target: /mnt/epx-results
    command: >
      sh -c "rm -fr dist
             python3 -m build
             twine upload --skip-existing --repository pypi dist/*"
