name: Release Pull Request Open

on:
  pull_request:
    types: [opened, synchronized, reopened]
    branches:
      - main

# TODO: Check release label

jobs:
  check_version:
    runs-on: ubuntu:latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check that VERSION file is valid
        run: docker-compose run check_version
